version: '3.8'
services:
  app:
    build: .
    container_name: wind-vpn-app
    restart: always
    ports:
      - "10000:10000"
      - "51820:51820/udp"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    privileged: true
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:alpine
    container_name: wind-vpn-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  wireguard_data:
  redis_data:
