version: '3.8'
services:
  app:
    build: .
    container_name: wind-vpn-app
    restart: always
    ports:
      - "10000:10000"
      - "51820:51820/udp"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /lib/modules:/lib/modules:ro
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
    privileged: true

volumes:
  wireguard_data:
